UPC.CA.ABET.Presentation/Areas/Rubric/ViewModels/BulkInsert/OutcomeReportViewModel.cs
#region Imports

using System;
using System.Collections.Generic;
using System.Linq;
using UPC.CA.ABET.Helpers;
using UPC.CA.ABET.Models;

#endregion

namespace UPC.CA.ABET.Presentation.Areas.Rubric.ViewModels.BulkInsert
{
    public class OutcomeReportViewModel
    {
        #region Propiedades

        public Int32 IdPeriodoAcademico { get; set; }
        public Int32 IdCarrera { get; set; }
        public Int32 IdCurso { get; set; }
        public string Prueba { get; set; }

        public List<PeriodoAcademico> lstPeriodoAcademico { get; set; }
        public List<Carrera> lstCarrera { get; set; }
        public List<Curso> lstCurso { get; set; }

        #endregion

        #region Metodos

        /// <summary>
        /// Carga todos los periodos académicos existentes y los cursos de proyectos
        /// </summary>
        /// <param name="DataContext">Context de la aplicación</param>
        /// <returns></returns>
        public void CargarDatos(CargarDatosContext DataContext, int? IdEscuela)
        {
            var context = DataContext.context;
            var IdCiclo = DataContext.session.GetPeriodoAcademicoId();

            lstPeriodoAcademico = (from submoda in context.SubModalidadPeriodoAcademico
                                   join pa in context.PeriodoAcademico on submoda.IdPeriodoAcademico equals pa.IdPeriodoAcademico
                                   where (submoda.IdSubModalidad == 1)
                                   select pa).ToList();
            lstCarrera = context.CarreraPeriodoAcademico.Where(x => x.SubModalidadPeriodoAcademico.IdPeriodoAcademico == IdCiclo && x.Carrera.IdEscuela == IdEscuela).Select(x => x.Carrera).ToList();
            lstCurso = context.CursosEvaluarRubrica.Where(x => x.SubModalidadPeriodoAcademicoModulo.SubModalidadPeriodoAcademico.IdPeriodoAcademico == IdCiclo && x.IdEscuela == IdEscuela).Select(x => x.Curso).ToList();
        }

        #endregion
    }
}

UPC.CA.ABET.Presentation/Areas/Rubric/ViewModels/BulkInsert/StatusReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UPC.CA.ABET.Presentation.Areas.Rubric.ViewModels.BulkInsert
{
    public class StatusReportViewModel
    {
        public String Codigo { get; set; }
        public String Nombre { get; set; }
        public String Docente { get; set; }
        public String Evaluador { get; set; }
        public String TipoCurso { get; set; }
    }
}

UPC.CA.ABET.Presentation/Areas/Upload/ViewModels/BeforeEnrollment/UploadExcelFilesViewModel.cs
#region Imports

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using UPC.CA.ABET.Helpers;
using UPC.CA.ABET.Models;
using UPC.CA.ABET.Presentation.Areas.Rubric.Resources.Views.BulkInsert;

#endregion

namespace UPC.CA.ABET.Presentation.Areas.Upload.ViewModels.BeforeEnrollment
{
    public class UploadExcelFilesViewModel
    {
        #region Propiedades

        [Required]
        public HttpPostedFileBase Archivo { get; set; }
        public BulkInsertType TipoCargaMasiva { get; set; }
        public String TituloPagina { get; set; }
        public String Icono { get; set; }
        public Dictionary<String, String> DicMensajes { get; set; }



        /*ROLES DISPONIBLES */
        public IEnumerable<TipoEvaluadorMaestra> lstTipoEvaluadorMaestra { get; set; }

        #endregion

        #region Metodos

        /// <summary>
        /// Carga los datos de la página correspondientes al tipo de carga masiva los cuales 
        /// son determinados según el tipo de carga masiva elegida en el sidebar principal,
        /// como también los mensajes de validaciones correspondientes almacenados en un 
        /// tipo de dato diccionario.
        /// </summary>
        /// <param name="TipoCargaMasiva">Enumerador que determina el tipo de carga masiva</param>
        /// <returns></returns>
        public void CargarDatos(BulkInsertType TipoCargaMasiva)
        {
            this.TipoCargaMasiva = TipoCargaMasiva;
            DicMensajes = new Dictionary<String, String>();
            DicMensajes.Add("HeadersInvalidos", UploadFilesResource.HeadersInvalidos);

            TituloPagina = "Carga de Notas Calificadas de RV";
            Icono = "plus-book";
        }

        #endregion
    }
}

UPC.CA.ABET.Presentation/Areas/Rubric/Controllers/BulkInsertController.cs
#region Imports

using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using UPC.CA.ABET.Presentation.Controllers;
using UPC.CA.ABET.Helpers;
using UPC.CA.ABET.Logic.Areas.Rubric.ExcelBulkInsert;
using UPC.CA.ABET.Presentation.Areas.Rubric.Resources.Views.BulkInsert;
using UPC.CA.ABET.Presentation.Areas.Rubric.ViewModels.BulkInsert;
using UPC.CA.ABET.Logic.Areas.Rubric.ExcelReports;
using ClosedXML.Excel;
using System.Linq;
using Ionic.Zip;
using UPC.CA.ABET.Presentation.Filters;
using UPC.CA.ABET.Models;

#endregion

namespace UPC.CA.ABET.Presentation.Areas.Rubric.Controllers
{

    public class BulkInsertController : BaseController
    {
        #region Get


        public ActionResult GetTemplate(BulkInsertType Type)
        {
            XLWorkbook objExcel = null;
            MemoryStream objStream = null;
            String nombreReporte = string.Empty;

            try
            {
                Int32 periodoAcademicoActualId = Context.PeriodoAcademico.FirstOrDefault(x => x.Estado.Equals(ConstantHelpers.ESTADO.ACTIVO)).IdPeriodoAcademico;

                switch (Type)
                {
                    case BulkInsertType.OutcomeGoalCommission:
                        nombreReporte = "";
                        break;
                    case BulkInsertType.VirtualCompany:
                        nombreReporte = "5.EMPRESAS VIRTUALES CARGA MASIVA.xlsx";
                        break;
                    case BulkInsertType.AcademicProject:
                        nombreReporte = "7.PROYECTOS ACADEMICOS CARGA MASIVA.xlsx";
                        break;
                    case BulkInsertType.EvaluationType:
                        nombreReporte = "3.TIPO DE EVALUACIONES CARGA MASIVA.xlsx";
                        break;
                    case BulkInsertType.EvaluatorType:
                        nombreReporte = "2.ROLES DE EVALUADORES CARGA MASIVA POR CURSO.xlsx";
                        break;
                    case BulkInsertType.Evaluation:
                        nombreReporte = "4.EVALUACIONES CARGA MASIVA.xlsx";
                        break;
                    case BulkInsertType.Evaluator:
                        nombreReporte = "EVALUADORES CARGA MASIVA.xlsx";
                        break;
                    case BulkInsertType.GrupoComite:
                        nombreReporte = "6.GRUPO COMITE CARGA MASIVA.xlsx";
                        break;  
                    case BulkInsertType.EvaluatorTypeMaster:
                        nombreReporte = "ROLES DE EVALUADORES CARGA MASIVA.xlsx";
                        break;
                    case BulkInsertType.CoursesToEvaluation:
                        nombreReporte = "1.CURSOS PARA EVALUAR RUBRICA CARGA MASIVA.xlsx";
                        break;
                    case BulkInsertType.RubricToEvaluation:
                        nombreReporte = "Formato_Carga_RV.xlsx";
                        break;
                    default:
                        break;
                }
                var path = Server.MapPath(ConstantHelpers.TEMP_PATH_REPORTS_RUBRICS + nombreReporte);

                objExcel = new XLWorkbook(path);
                objStream = new MemoryStream();

                objExcel.SaveAs(objStream);
                byte[] fileBytes = objStream.ToArray();

                return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, nombreReporte);
            }
            catch (Exception ex)
            {
                PostMessage(MessageType.Error, ex.Message);
                return RedirectToAction("Index", "Home");
            }
            finally
            {
                if (objStream != null)
                {
                    objStream.Dispose();
                    objStream = null;
                }
                if (objExcel != null)
                {
                    objExcel.Dispose();
                    objExcel = null;
                }
            }
        }

        [AuthorizeUserAttribute(AppRol.CoordinadorCarrera)]
        public ActionResult IndexUpload()
        {
            return View();
        }


        [AuthorizeUserAttribute(AppRol.CoordinadorCarrera)]
        /// <summary>
        /// Retorna la página de Carga Masiva de Archivos Excel, la cual es renderizada según el
        /// tipo de carga elegida en el sidebar principal.
        /// </summary>
        /// <param name="Type">Enumerador que determina el tipo de carga masiva</param>
        /// <returns>View</returns>
        public ActionResult UploadExcelFiles(BulkInsertType Type = BulkInsertType.VirtualCompany)
        {
            var viewModel = new UploadExcelFilesViewModel();
            viewModel.CargarDatos(Type);

            if(Type == BulkInsertType.EvaluatorType)
            {
                viewModel.lstTipoEvaluadorMaestra = Context.TipoEvaluadorMaestra.ToList();
            }

            TempData["DicMensajes"] = viewModel.DicMensajes;
            return View(viewModel);
        }

        //[AuthorizeUserAttribute(AppRol.CoordinadorCarrera)]
        public ActionResult OutcomeReport()
        {
            var viewModel = new OutcomeReportViewModel();
            viewModel.CargarDatos(CargarDatosContext(),this.EscuelaId);
            return View(viewModel);
        }


        //[AuthorizeUserAttribute(AppRol.CoordinadorCarrera)]
        public ActionResult DownloadQualifyStatus()
        {

            return View();
        }
        //comentario de pruebas
        //[AuthorizeUserAttribute(AppRol.CoordinadorCarrera)]
        public ActionResult DownloadReport (String Name)
        {
            MemoryStream objStream = null;
            List<String> lstRutas = null;
            try
            {
                var templatePath = Server.MapPath(Path.Combine(ConstantHelpers.TEMP_PATH_REPORTS_RUBRICS, ConstantHelpers.TEMPLATE_STATUS_REPORT));
                string nombreReporte = string.Empty;

                if (Name.Equals("Pendientes"))
                {
                    var proyectosPendientes = Context.sp_LstProyectosPendientes(this.EscuelaId).ToList();
                    var objExcel = new XLWorkbook(templatePath);
                    var worksheet = objExcel.Worksheet(1);
                    nombreReporte = "Estatus Calificaciones pendientes.xlsx";
                    worksheet.Name = "Pendientes de calificacion";
                    int cont = 2;
                    foreach (var item in proyectosPendientes)
                    {
                        worksheet.Cell("A" + cont).Value = item.Codigo;
                        worksheet.Cell("B" + cont).Value = item.Nombre;
                        worksheet.Cell("C" + cont).Value = item.Docente;
                        worksheet.Cell("D" + cont).Value = item.Evaluador;
                        cont++;
                    }

                    objStream = new MemoryStream();

                    objExcel.SaveAs(objStream);
                    byte[] fileBytes = objStream.ToArray();

                    return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, nombreReporte);
                }
                else
                {
                    var proyectosListosACalificart = Context.sp_LstProyectosACalificarComite().ToList();
                    var objExcel = new XLWorkbook(templatePath);
                    var worksheet = objExcel.Worksheet(1);
                    nombreReporte = "Estaus Proyectos listos.xlsx";
                    worksheet.Name = "Listos a calificar por Comite";
                    int cont = 2;
                    worksheet.Cell("C1").Value = "Curso";
                    worksheet.Cell("D1").Value = "Docente";
                    foreach (var item in proyectosListosACalificart)
                    {
                        worksheet.Cell("A" + cont).Value = item.Codigo;
                        worksheet.Cell("B" + cont).Value = item.Nombre;
                        worksheet.Cell("C" + cont).Value = item.TipoCurso;
                        worksheet.Cell("D" + cont).Value = item.Docente;
                        cont++;
                    }

                    objStream = new MemoryStream();

                    objExcel.SaveAs(objStream);
                    byte[] fileBytes = objStream.ToArray();

                    return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, nombreReporte);
                }
            }
            catch (Exception ex)
            {
                PostMessage(MessageType.Error, ex.Message);
                return RedirectToAction("DownloadQualifyStatus");
            }
            finally
            {
                if (objStream != null)
                {
                    objStream.Dispose();
                    objStream = null;
                }

                if (lstRutas != null)
                {
                    foreach (var ruta in lstRutas)
                    {
                        if (System.IO.File.Exists(ruta))
                        {
                            System.IO.File.Delete(ruta);
                        }
                    }
                }
            }
        }

        [HttpGet]
        public ActionResult DownloadEvaluatorOutcomeReportGet(Int32? ProyectoId, Int32? EvaluacionId)
        {
            XLWorkbook objExcel = null;
            MemoryStream objStream = null;

            try
            {
                Int32 periodoAcademicoActualId = Context.PeriodoAcademico.FirstOrDefault(x => x.Estado.Equals(ConstantHelpers.ESTADO.ACTIVO)).IdPeriodoAcademico;
                String nombreReporte = "Reporte de Outcomes por Evaluador.xlsx";
                var path = Server.MapPath(ConstantHelpers.TEMP_PATH_REPORTS_RUBRICS + ConstantHelpers.TEMPLATE_OUTCOME_EVALUADOR);

                objExcel = ExcelReportLogic.GenerateOutcomeEvaluatorReport(Context, path, periodoAcademicoActualId, ProyectoId.Value, EvaluacionId.Value, ref nombreReporte);

UPC.CA.ABET.Presentation/Areas/Rubric/Views/BulkInsert/DownloadQualifyStatus.cshtml
@using UPC.CA.ABET.Presentation.Areas.Rubric.Resources.Views.BulkInsert
@{
    ViewBag.Title = BulkInsertResource.DescargarStatusDeCalificacion;
    ViewBag.Icon = "file-archive-o";
}


<div class="panel">

    <div class="panel-header">
        <h5 class="panel-title"><i class="fa fa-info"></i> @BulkInsertResource.EstatusDeCalificacion</h5>
    </div>

    <div class="panel-body">
        <p>@BulkInsertResource.EscogaUnaOpcion</p>

        <a class="btn btn-dark" href="@Url.Action("DownloadReport", "BulkInsert", new { Name = "Pendientes" })"><i class="fa fa-percent"></i>&nbsp; @BulkInsertResource.PendientesTodosLosRolesMenosComite</a>
        <!--<a class="btn btn-dark" href="@Url.Action("DownloadReport", "BulkInsert", new { Name = "Listos" })"><i class="fa fa-check"></i>&nbsp; Listas para comite</a>-->
    </div>

</div>

UPC.CA.ABET.Presentation/Areas/Rubric/Views/BulkInsert/IndexUpload.cshtml
@model UPC.CA.ABET.Presentation.Areas.Rubric.ViewModels.BulkInsert.UploadExcelFilesViewModel
@using UPC.CA.ABET.Presentation.Resources.Areas.Rubric

@{
	ViewBag.Title = UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.TitleIndexUpdate;
}


@section Breadcrumbs{
}

@section SecondSidebar
{
	@{Html.RenderPartial("_SecondSidebar");}
}

<h5><span class="fa fa-arrow-left"></span>&nbsp; @UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.HeaderUploadIndex</h5>
<br />

<ul>
    <li><h5>&nbsp; @UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.MessageCargarGenerales</h5></li>
    <li><h5>&nbsp; @UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.MessageInstrucciones</h5></li>
</ul>

UPC.CA.ABET.Presentation/Areas/Rubric/Views/BulkInsert/OutcomeReport.cshtml
@model UPC.CA.ABET.Presentation.Areas.Rubric.ViewModels.BulkInsert.OutcomeReportViewModel
@using UPC.CA.ABET.Presentation.Resources.Areas.Rubric

@{
	ViewBag.Title = UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.TituloE;
	ViewBag.Icon = "file-archive-o";
	var cookie = CookieHelpers.GetCookie(CookieKey.Culture);
	var language = cookie != null ? cookie.Value.ToString() : ConstantHelpers.CULTURE.ESPANOL;
}

@section Styles {
	@Html.Content("css/more-styles.css", ConstantHelpers.AREAS.RUBRIC)
}

@section Breadcrumbs {
}


@*<div class="row">

		<div class="col-md-12">
			<div class="panel">
				<div class="panel-header">
					<h5 class="panel-title"><i class="fa fa-info"></i> Estatus de calificación</h5>
				</div>
				<div class="panel-body">
					<div class="panel-footer text-right">
						<a href="@Url.Action("DownloadReport", "BulkInsert", new { Name = "Pendientes" })" id="download" class="btn btn-primary">
							<i class="fa fa-download"></i>
							@RubricResource.Descargar
						</a>
					</div>
				</div>

			</div>
		</div>
	</div>*@
<div class="row">
	<div class="panel filters">
		@Html.PanelHeader(String.Format("<i class=\"fa fa-filter\"></i> {0}", @UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.Consolidado))
        <div class="panel-body row">
            @using (Html.BeginForm("DownloadStudentGradeReport", "BulkInsert", FormMethod.Post, new { @id = "formZipReport" }))
            {
                <div class="panel-footer text-right">
                    <button type="submit" id="download" class="btn btn-primary">
                        <i class="fa fa-download"></i>
                        @UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.Descargar
                    </button>
                </div>
            }
        </div>
	</div>
</div>

<div class="row">
	<div class="panel filters">
		@Html.PanelHeader(String.Format("<i class=\"fa fa-filter\"></i> {0}", @UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.Evidencia))
		<div class="panel-body row">
			@using (Html.BeginForm("DownloadZipReport", "BulkInsert", FormMethod.Post))
			{
				@Html.FormGroup(UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.Ciclo,
								Html.DropDownListFor(m => m.IdPeriodoAcademico, new SelectList(Model.lstPeriodoAcademico, "IdPeriodoAcademico", "CicloAcademico"),
								new {
									@class = "form-control",
									@data_plugin = "select2",
									@data_id = "Cb_Ciclo"
								}))
				@Html.FormGroup(UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.Carrera,
								Html.DropDownListFor(m => m.IdCarrera, new SelectList(Model.lstCarrera, "IdCarrera", "NombreEspanol"),
								new
								{
									@class = "form-control",
									@data_plugin = "select2",
									@data_id = "Cb_Carrera"
								}))
				@Html.FormGroup(UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.Curso,
								Html.DropDownListFor(m => m.IdCurso, new SelectList(Model.lstCurso, "IdCurso", "NombreEspanol"),
								new {
									@class = "form-control",
									@data_plugin = "select2"
								}))

				<div class="panel-footer text-right">
                    <button type="submit" id="download" class="btn btn-primary eer">
                        <i class="fa fa-download"></i>
                        @UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.Descargar
                    </button>
				</div>
			}
		</div>
	</div>
</div>

@section Scripts {

	<script>

        @*$('*[data-id="Cb_Ciclo"]').change(function () {
            var comboFillCarrera = $('*[data-id="Cb_Carrera"]');
            $.ajax({
                url: '@Url.Action("GetCarreraByCiclo", "Rubric")',
                type: "POST",
                data: {
                    IdCiclo: $(this).val()
                },
                dataType: 'json',
                beforeSend: function () {
                    comboFillCarrera.attr("disabled", "disabled");
                    comboFillCarrera.empty();
                    comboFillCarrera.append('<option value="">@UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.Cargando... </option>');
                },
                success: function (data) {
                    var Carreras = data;
                    if (Carreras.length > 0) {
                        comboFillCarrera.empty();
                        comboFillCarrera.removeAttr("disabled");
                        for (var i = 0; i < Carreras.length; i++) {
                            comboFillCarrera.append('<option value="' + Carreras[i]['IdCarrera'] + '">' + Carreras[i]['NombreEspanol'] + '</option>');
                        }
                    } else {
                        comboFillCarrera.removeAttr("disabled");
                        comboFillCarrera.empty();
                        comboFillCarrera.append('<option value="">@UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.NoExisteRegistros</option>');
                    }
                },
                error: function () {
                    comboFillCarrera.removeAttr("disabled");
                    comboFillCarrera.append('<option value="">@UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.OcurrioError</option>');
                }
            });
        });*@

        $('#download.btn.btn-primary.eer').on("click", function () {
            var result = $('#formZipReport').valid()
            if (result == false) {
                error("Se deben de completar todos los campos.")
                return false
            }

        });

	</script>

	<script>
        function error(message) {
            swal({
                title: message,
                type: 'error'
            });
        }

        function showLoading() {
            swal({
                title: '@language' == "es-PE" ? "Cargando..." : "Loading...",
                text: '<i class="fa fa-cog fa-spin fa-3x fa-fw margin-bottom"></i>',
                showConfirmButton: false,
                html: true
            });
        }

        function closeLoading() {
            swal.close();
        }
	</script>
}

UPC.CA.ABET.Presentation/Areas/Rubric/Views/BulkInsert/UploadExcelFiles.cshtml
@using UPC.CA.ABET.Presentation.Areas.Rubric.Resources.Views.BulkInsert
@model UPC.CA.ABET.Presentation.Areas.Rubric.ViewModels.BulkInsert.UploadExcelFilesViewModel
@using UPC.CA.ABET.Presentation.Resources.Areas.Rubric

@{
	ViewBag.Title = Model.TituloPagina;

}

@section Styles {
	<link rel="stylesheet" href="@Url.Content("~/Content/vendor/dropify/dropify.min.css")">
}

@section Breadcrumbs{
}

<style>
	#tablaEvaluadorType {
		padding: 10px;
	}
</style>
@section SecondSidebar
{
	@{Html.RenderPartial("_SecondSidebar");}
}
<div class="row">
	@if (Model.TipoCargaMasiva == BulkInsertType.EvaluatorType)
	{
		<div class="col-md-12">
			<div class="panel" id="tablaEvaluadorType">
				<div class="table-responsive">
					<table class="table table-hover" id="myTable">
						<thead>
							<tr>
								<th>
									@BulkInsertResource.Codigo
								</th>
								<th>
									@BulkInsertResource.Nombre
								</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model.lstTipoEvaluadorMaestra)
							{
								<tr>
									<td>
										@Html.DisplayFor(modelItem => item.Codigo)
									</td>
									<td>
										@Html.DisplayFor(modelItem => item.Nombre)
									</td>
								</tr>
							}
						</tbody>

					</table>
				</div>
			</div>
		</div>
	}
	<div class="col-md-12">
		<div class="panel">
			@Html.PanelHeader(String.Format("<i class=\"fa fa-file-o\"></i> {0}", UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.ElegirArchivo))

			@using (Html.BeginForm("UploadExcelFiles", "BulkInsert", FormMethod.Post, new { enctype = "multipart/form-data" }))
			{
				@Html.HiddenFor(x => x.TituloPagina)
				@Html.HiddenFor(x => x.Icono)
				@Html.HiddenFor(x => x.TipoCargaMasiva)

				<div class="panel-body">
					@Html.TextBoxFor(x => x.Archivo, new { type = "file", @class = "dropify" })
				</div>



				<div class="panel-footer text-right">
					<a class="btn btn-default" id="btn-download-template" href="@Url.Action("GetTemplate","BulkInsert", new { Type = Model.TipoCargaMasiva })">
						<i class="fa fa-download"></i>&nbsp; @UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.DescargarPlantilla
					</a>

					<button type="submit" class="btn btn-primary" id="btn-upload">
						<i class="fa fa-upload"></i>&nbsp; @UPC.CA.ABET.Presentation.Resources.Areas.Rubric.RubricResource.SubirArchivo
					</button>
				</div>
			}
		</div>
	</div>
</div>

@section Scripts {
	<script src="@Url.Content("~/Content/vendor/dropify/dropify.min.js")"></script>
	<script type="text/javascript">

        $('.dropify').dropify();

        $('#btn-upload').click(function () {
            var file = $('#Archivo').val();

            if (file == '') {
                swal("El campo Archivo es obligatorio.", "", "error");
                allowSubmit = false;
            }
            else {
                allowSubmit = true
            }           
            console.log(allowSubmit);
            console.log(file);
			return allowSubmit;
		});
	</script>
}